name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  lint-and-format-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Check TypeScript errors
        run: tsc --noEmit
      - name: Lint Test
        run: npm run lint:check
      - name: Format Test
        run: npm run format:check
